import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import "~/styles/globals.css";

export const metadata = {
  title: "Homely",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const poppins = Poppins({ subsets: ["latin"], variable: "--inter", weight:['100',"200","300","400", "500","600","700","800"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
