import { type ReactNode } from "react";
import { LandlordSidebar } from "./_components/landlord-Sidebar";

export const metadata = {
  title: "Homely | Land Lord Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};
export default function LandlordDashboardLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <div className="flex h-screen " suppressHydrationWarning>
      <div className="w-16 text-white lg:w-64">
        <LandlordSidebar />
        {/* <p>Side bar</p> */}
      </div>
      <div className=" flex-1 overflow-hidden overflow-y-scroll p-6">
        {children}
      </div>
    </div>
  );
}
